site_name: Documentation
repo_url: https://github.com/dyalog/documentation
copyright: Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener"><strong>Material for MkDocs</strong></a><br/>Copyright &copy; 1982-$CURRENT_YEAR <strong><a href="https://dyalog.com" target="_blank" rel="noopener">Dyalog Limited</a></strong> ($BUILD_DATE $GIT_INFO).<br/>Except where otherwise noted, content on this site is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"><strong>Creative Commons Attribution 4.0 International</strong></a> licence. 


theme:
  favicon: 'documentation-styles/images/favicon-32.png'
  logo: documentation-styles/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.sections
  name: material
  font:
      text: Be Vietnam Pro

extra_css:
  - documentation-styles/css/main.css
  - documentation-styles/css/extra.css
  - documentation-styles/css/admonition-ucmdhelp.css
  - documentation-styles/css/windows-ui-guide.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - privacy
  - search
  - macros
  - monorepo
  - minify:
      minify_html: true
  - caption:
      table: 
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom

extra:
  version_maj: 20
  version_min: 0
  version_majmin: 20.0
  version_condensed: 200
  conga_version: 3.6
  conga_version_condensed: 36
  version:
    provider: mike
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      pygments_lang_class: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page

nav:
  - Conventions: conventions.md
  - 'Core Reference':
        - 'Dyalog APL Language': "!include ./language-reference-guide/mkdocs.yml"
        - 'Programming': "!include ./programming-reference-guide/mkdocs.yml"
  - 'Dyalog for Microsoft Windows':
        - 'Installation/Configuration': "!include ./windows-installation-and-configuration-guide/mkdocs.yml"
        - 'User Interface': "!include ./windows-ui-guide/mkdocs.yml"
        - 'Object Reference': "!include ./object-reference/mkdocs.yml"
        - 'Interfaces': "!include ./interface-guide/mkdocs.yml"
        - '.NET Framework Interface': "!include ./dotnet-framework-interface/mkdocs.yml"
  - 'Dyalog for UNIX': 
        - 'Installation/Configuration': "!include ./unix-installation-and-configuration-guide/mkdocs.yml"       
        - 'User Interface': "!include ./unix-user-guide/mkdocs.yml"
  - 'Release Notes':
        - 'v20.0 Release Notes': "!include ./release-notes/mkdocs.yml"
        - 'Earlier Release Notes': "!include ./earlier-release-notes/mkdocs.yml"
  - 'About':
        - 'Third-party Licences': licences-overview.md
        - 'Trademarks': trademarks.md